const {launchBrowser}=require('./browser.cjs'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await launchBrowser();try{
 const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://api.open-meteo.com/**',r=>r.abort());await p.goto(pathToFileURL(path.resolve('docs/design/mockup.html')).href);await p.locator('#theme-toggle').click();
 const check=async()=>{const failures=await p.evaluate(()=>{
  const rgb=s=>(s.match(/[\d.]+/g)||[]).slice(0,3).map(Number),lum=c=>c.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((n,v,i)=>n+v*[.2126,.7152,.0722][i],0);
  return [...document.querySelectorAll('#content select,#content input:not([type=checkbox]),#content textarea,.operation-filters,.staffing-bulk,.stat-note,.read-only')].filter(e=>e.getClientRects().length&&!e.disabled).flatMap(e=>{const s=getComputedStyle(e),bg=lum(rgb(s.backgroundColor)),fg=lum(rgb(s.color)),ratio=(Math.max(bg,fg)+.05)/(Math.min(bg,fg)+.05);return bg>.3||ratio<4.5?[{element:e.id||e.className,bg:s.backgroundColor,color:s.color,ratio}]:[];});});assert.deepEqual(failures,[]);};
 for(const name of ['operations','statistics','personnel','duty','equipment','requests','gps']){await p.locator('nav [data-page='+name+']').click();await check();if(name==='operations'){await p.locator('[data-operation-tab=schedule]').click();await check();await p.screenshot({path:'tmp/test-results/dark-operation-filters.png'});}if(name==='statistics')await p.screenshot({path:'tmp/test-results/dark-period-filters.png'});}
 await p.locator('#demo-role').selectOption('viewer');await p.locator('nav [data-page=operations]').click();await check();await p.locator('[data-viewer-wing=a]').click();await check();
 await p.locator('#demo-role').selectOption('bnoc');await p.locator('nav [data-page=operations]').click();await p.locator('[data-operation-node=""]').click();assert.equal(await p.locator('#system-operation-form select').first().evaluate(e=>getComputedStyle(e).color),'rgb(228, 236, 247)');await p.locator('#close').click();await p.locator('#theme-toggle').click();assert.equal(await p.locator('.operation-filters').first().evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(255, 255, 255)');assert.deepEqual(errors,[]);console.log('PASS dark controls: 7 menus, schedule/period filters, viewer and dialog, contrast >=4.5, light mode preserved');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
