const {launchBrowser}=require('./browser.cjs'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await launchBrowser();try{
const p=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://api.open-meteo.com/**',r=>r.abort());await p.goto(pathToFileURL(path.resolve('docs/design/mockup.html')).href);await p.evaluate(()=>equipmentReady);
await p.evaluate(async()=>{equipmentDocuments.push({id:nextDocumentId++,file:new File(['test'],'공유 공문.pdf',{type:'application/pdf'}),project:'검증 사업',year:'2026',equipmentIds:[1,2]},{id:nextDocumentId++,file:new File(['test'],'미연결.pdf'),project:'검증 사업',year:'2026',equipmentIds:[]});await saveEquipmentData();});
await p.locator('nav [data-page=equipment]').click();assert.equal(await p.locator('#equipment-documents').isVisible(),false);await p.locator('[data-equipment-tab=security]').click();await p.locator('#equipment-documents').click();assert.match(await p.locator('#dialog-body').textContent(),/미연결.pdf/);await p.locator('[data-document-delete]').first().click();assert.match(await p.locator('#document-delete-form').textContent(),/EQ-0001/);assert.match(await p.locator('#document-delete-form').textContent(),/EQ-0002/);await p.locator('[data-document-back]').click();assert.equal(await p.evaluate(()=>equipmentDocuments.length),2);
await p.locator('[data-document-delete]').first().click();await p.locator('[name=filename]').fill('틀린 파일명');await p.locator('#document-delete-form .primary').click();assert.match(await p.locator('.error').textContent(),/일치/);await p.locator('[name=filename]').fill('공유 공문.pdf');await p.evaluate(()=>{window.originalSave=saveEquipmentData;saveEquipmentData=async()=>{throw Error('test failure');};});await p.locator('#document-delete-form .primary').click();assert.match(await p.locator('.error').textContent(),/공문은 유지/);assert.equal(await p.evaluate(()=>documentsFor(1).length),1);await p.evaluate(()=>{saveEquipmentData=window.originalSave;});await p.locator('#document-delete-form .primary').click();await p.waitForFunction(()=>document.querySelector('#dialog-title').textContent==='업체 공문 관리');assert.equal(await p.evaluate(()=>documentsFor(1).length+documentsFor(2).length),0);assert.equal(await p.evaluate(()=>equipment.find(e=>e.id===2).status),'설치 불가');
await p.locator('[data-document-delete]').click();await p.locator('[name=filename]').fill('미연결.pdf');await p.locator('#document-delete-form .primary').click();await p.waitForFunction(()=>document.querySelector('#dialog-title').textContent==='업체 공문 관리');assert.match(await p.locator('#dialog-body').textContent(),/등록된 공문이 없습니다/);await p.reload();await p.evaluate(()=>equipmentReady);assert.equal(await p.evaluate(()=>equipmentDocuments.length),0);
assert.equal(await p.evaluate(()=>{state.role='user';return canManageEquipmentDocuments();}),false);assert.equal(await p.evaluate(()=>{state.role='viewer';return canManageEquipmentDocuments();}),false);assert.deepEqual(errors,[]);console.log('PASS documents: shared/orphan deletion, cancel, filename validation, persistence, failure rollback, permissions');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
