const {launchBrowser}=require('./browser.cjs'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await launchBrowser();try{
 const p=await browser.newPage({viewport:{width:1366,height:768}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://api.open-meteo.com/**',r=>r.abort());await p.goto(pathToFileURL(path.resolve('docs/design/mockup.html')).href);
 await p.locator('#theme-toggle').click();assert.equal(await p.locator('html').getAttribute('data-theme'),'dark');await p.reload();assert.equal(await p.locator('html').getAttribute('data-theme'),'dark');
 await p.locator('#demo-role').selectOption('user');await p.evaluate(()=>M.createRequest(state,{target:'알림 UI 검증',type:'점검',description:'시험',wish:'network',tag:'PC'}));await p.locator('#demo-role').selectOption('bnoc');assert.equal(await p.locator('#inbox-button .badge').textContent(),'1');
 await p.locator('#inbox-button').click();await p.locator('#dialog [data-inbox-open]').click();assert.equal(await p.locator('#assignment-form').count(),1);await p.locator('#assignment-form [name=department]').selectOption('network');await p.locator('#assignment-form .primary').click();
 await p.locator('#demo-role').selectOption('network');assert.equal(await p.locator('#inbox-button .badge').textContent(),'1');await p.locator('#inbox-button').click();await p.locator('#dialog [data-inbox-open]').click();assert.equal(await p.locator('#task-form').count(),1);assert.equal(await p.evaluate(()=>state.tasks.find(t=>t.requestId===state.requests.at(-1).id).confirmed),false);await p.locator('#close').click();
 await p.reload();await p.locator('#demo-role').selectOption('network');assert.equal(await p.locator('#inbox-button .badge').textContent(),'0');await p.locator('#demo-role').selectOption('radio');await p.locator('#inbox-button').click();assert.equal(await p.locator('#dialog [data-inbox-open]').count(),0);await p.locator('#close').click();
 await p.locator('#demo-role').selectOption('bnoc');await p.locator('nav [data-page=operations]').click();await p.locator('#display').click();
 for(const size of [{width:1366,height:768},{width:1920,height:1080}]){await p.setViewportSize(size);assert.equal(await p.evaluate(()=>document.documentElement.scrollHeight<=innerHeight+1),true);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:'tmp/test-results/display-dark-'+size.width+'.png'});}
 await p.locator('[data-display-section=maintenance]').click();assert.equal(await p.locator('.display-board.single').count(),1);await p.locator('#display').click();assert.equal(await p.locator('#title').textContent(),'정보통신 운영현황');
 for(const page of ['dashboard','operations','personnel','duty','statistics','equipment','instructions','cpcon','gps']){await p.locator('nav [data-page='+page+']').click();assert.equal(await p.locator('html').getAttribute('data-theme'),'dark');}
 await p.locator('#demo-role').selectOption('viewer');await p.locator('#display').click();assert.equal(await p.locator('[data-display-section=duty]').count(),0);assert.doesNotMatch(await p.locator('#content').textContent(),/가상 가온|가상 하늘/);await p.locator('#display').click();
 await p.setViewportSize({width:1280,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await p.screenshot({path:'tmp/test-results/experience-desktop.png'});assert.deepEqual(errors,[]);console.log('PASS experience UI: inbox flow/persistence, theme, display fit at 1366/1920, exit restoration, roles and desktop');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
