const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs/promises'),{pathToFileURL}=require('node:url');const JSZip=require('../docs/design/mockup/vendor/jszip.min.js');
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.TEST_BROWSER_PATH?{executablePath:process.env.TEST_BROWSER_PATH}:{})});try{
 const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('https://api.open-meteo.com/**',r=>r.abort());await page.goto(pathToFileURL(path.resolve('docs/design/mockup.html')).href);
 await page.locator('nav [data-page=personnel]').click();await page.locator('#staffing-date').fill('2026-09-09');assert.equal(await page.locator('#report-day').inputValue(),'2026-09-09');
 await page.evaluate(()=>{state.personnel[0].name='=1+1';});let pending=page.waitForEvent('download');await page.locator('.report-export-menu').evaluate(e=>e.open=true);await page.locator('[data-report-daily]').click();let download=await pending;assert.equal(download.suggestedFilename(),'일일현황_2026-09-09.xlsx');let zip=await JSZip.loadAsync(await fs.readFile(await download.path()));let workbook=await zip.file('xl/workbook.xml').async('string');assert.equal((workbook.match(/<sheet /g)||[]).length,6);let people=await zip.file('xl/worksheets/sheet1.xml').async('string');assert.match(people,/=1\+1/);assert.doesNotMatch(people,/<f[ >]/);assert.match(people,/state="frozen"/);
 const daily=await page.evaluate(()=>dailyReport('2026-09-17'));assert.equal(daily.length,4);assert.equal(daily[1].rows.length,0);assert.match(daily[1].note,/미등록/);assert.equal(daily[3].rows.length,1);assert.match(daily[2].note,/과거 운영상태가 아님/);
 await page.locator('nav [data-page=statistics]').click();await page.locator('#statistics-form [name=start]').fill('2026-09-05');await page.locator('.report-export-menu').evaluate(e=>e.open=true);await page.locator('[data-report-maintenance]').click();assert.match(await page.locator('#feedback').textContent(),/먼저 조회/);await page.locator('#statistics-form [name=department]').selectOption('radio');await page.locator('#statistics-form .primary').click();pending=page.waitForEvent('download');await page.locator('.report-export-menu').evaluate(e=>e.open=true);await page.locator('[data-report-maintenance]').click();download=await pending;assert.equal(download.suggestedFilename(),'정비현황_2026-09-05_2026-09-16.xlsx');zip=await JSZip.loadAsync(await fs.readFile(await download.path()));workbook=await zip.file('xl/workbook.xml').async('string');assert.equal((workbook.match(/<sheet /g)||[]).length,2);const detail=await zip.file('xl/worksheets/sheet2.xml').async('string');assert.match(detail,/무선체계반/);assert.doesNotMatch(detail,/네트워크체계반/);
 await page.locator('#demo-role').selectOption('network');const technician=await page.evaluate(()=>maintenanceReport({start:'2026-09-01',end:M.today,department:'radio'}));assert.ok(technician[1].rows.every(r=>r[2]==='네트워크체계반'));
 await page.locator('#demo-role').selectOption('viewer');const viewer=await page.evaluate(()=>{viewerFilters.wing='a';return {daily:dailyReport('2026-09-18'),period:maintenanceReport(viewerFilters)};});assert.equal(viewer.daily.length,2);assert.ok(viewer.daily[0].rows.every(r=>r[0]==='가상 비행단 A'));assert.ok(viewer.period[1].rows.every(r=>r[0]==='가상 비행단 A'));
 await page.locator('#demo-role').selectOption('user');assert.equal(await page.evaluate(()=>dailyReport(M.today).length),3);assert.equal(await page.evaluate(()=>{try{maintenanceReport({start:M.today,end:M.today});return false;}catch{return true;}}),true);
 assert.equal(await page.evaluate(()=>{try{dailyReport('2026-02-30');return false;}catch{return true;}}),true);assert.deepEqual(errors,[]);console.log('PASS Excel: actual downloads, date synchronization, sheets, missing roster, schedules, safe text, applied periods, department/viewer scope and permissions');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
