const {launchBrowser}=require('./browser.cjs');
const assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
(async()=>{
 const browser=await launchBrowser();
 try{
  const page=await browser.newPage({viewport:{width:1512,height:1100}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.route('https://api.open-meteo.com/**',r=>r.abort());
  await page.goto(pathToFileURL(path.resolve('docs/design/mockup.html')).href);
  assert.match(await page.locator('.gps-tile').textContent(),/정상.*제17전투비행단.*청주/s);
  await page.locator('.gps-tile').click();
  assert.equal(await page.locator('#gps-filter [name=region]').inputValue(),'cheongju');
  assert.equal(await page.locator('.gps-table tbody tr').count(),1);
  await page.locator('[data-gps-reset]').click();
  assert.deepEqual(await page.locator('.gps-summary strong').allTextContents(),['2','1','1','1','1']);
  assert.equal(await page.locator('[data-gps-alert=actual] .gps-alert-current').textContent(),'관심');
  assert.equal(await page.locator('[data-gps-alert=exercise] .gps-alert-current').textContent(),'경계');
  assert.equal(await page.locator('.gps-alert-scale span').count(),8);
  const alertsBefore=await page.locator('.gps-alerts').textContent();
  assert.equal(await page.locator('.gps-detector-marker svg').count(),3);
  await page.locator('.gps-detector-marker[data-gps-detector=east]').click();
  assert.match(await page.locator('#gps-detector-detail').textContent(),/탐지 C.*장비 \/ 네트워크 장애/s);
  await page.locator('.gps-detector-list [data-gps-detector=central]').click();
  assert.equal(await page.locator('.gps-detector-marker.selected').getAttribute('data-gps-detector'),'central');
  await page.locator('.gps-marker[data-gps-site=gangneung]').click();
  assert.match(await page.locator('#gps-detail').textContent(),/강릉.*기만.*3개.*26m/s);
  assert.equal(await page.locator('.gps-marker').count(),6);
  await page.locator('.gps-marker[data-gps-site=seonggeo]').click();
  assert.match(await page.locator('#gps-detail').textContent(),/성거산.*경고/s);
  assert.equal(await page.locator('.gps-table .selected button').textContent(),'성거산');
  await page.screenshot({path:'tmp/test-results/gps-preview-gps.png',fullPage:true});
  await page.locator('.gps-table [data-gps-site=sacheon]').click();
  assert.equal(await page.locator('.gps-marker.selected').getAttribute('data-gps-site'),'sacheon');
  await page.locator('#gps-filter [name=status]').selectOption('missing');
  await page.locator('#gps-filter button.primary').click();
  assert.equal(await page.locator('.gps-marker').count(),1);
  assert.match(await page.locator('#gps-detail').textContent(),/가상 감시국.*장애.*확인 불가/s);
  await page.locator('#gps-filter [name=region]').selectOption('cheongju');
  await page.locator('#gps-filter button.primary').click();
  assert.equal(await page.locator('.gps-marker').count(),0);
  assert.equal(await page.locator('#gps-detail').count(),0);
  assert.equal(await page.locator('.gps-detector-marker').count(),3);
  assert.equal(await page.locator('.gps-alerts').textContent(),alertsBefore);
  await page.locator('[data-gps-reset]').click();
  await page.locator('.gps-basemap').evaluate(image=>image.decode());
  for(const width of [1512,1280,1920]){
   await page.setViewportSize({width,height:844});
   assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
   const overlaps=await page.locator('.gps-marker,.gps-detector-marker').evaluateAll(markers=>{
    const boxes=markers.map(marker=>({id:marker.dataset.gpsSite||marker.dataset.gpsDetector,rect:marker.getBoundingClientRect()}));
    return boxes.flatMap((a,i)=>boxes.slice(i+1).filter(b=>a.rect.left<b.rect.right&&a.rect.right>b.rect.left&&a.rect.top<b.rect.bottom&&a.rect.bottom>b.rect.top).map(b=>`${a.id}/${b.id}`));
   });
   assert.deepEqual(overlaps,[],`GPS marker labels overlap at ${width}px`);
   if(width===1280)await page.screenshot({path:'tmp/test-results/gps-preview-1280.png',fullPage:true});
  }
  await page.locator('#theme-toggle').click();
  assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
  await page.setViewportSize({width:1280,height:900});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
  await page.screenshot({path:'tmp/test-results/gps-preview-dark.png',fullPage:true});
  await page.locator('#theme-toggle').click();
  await page.setViewportSize({width:1512,height:1100});
  await page.locator('#demo-role').selectOption('viewer');
  await page.locator('.viewer-comparison [data-gps-open=seonggeo]').click();
  assert.match(await page.locator('#gps-detail').textContent(),/성거산.*경고/s);
  await page.locator('#demo-role').selectOption('network');
  await page.locator('nav [data-page=dashboard]').click();
  await page.locator('nav [data-page=gps]').click();await page.locator('[data-gps-reset]').click();await page.locator('[data-gps-site=cheongju]').first().click();assert.match(await page.locator('#gps-detail').textContent(),/청주/);
  assert.deepEqual(errors,[]);
  console.log('PASS GPS: dashboard mapping, map/list selection, filters, empty state, viewer, role switch, desktop');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
