const {launchBrowser}=require('./browser.cjs'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await launchBrowser();try{
 const page=await browser.newPage({viewport:{width:1512,height:1100}}),errors=[];
 page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE:',e.message);});await page.route('https://api.open-meteo.com/**',r=>r.abort());
 const url=pathToFileURL(path.resolve('docs/design/mockup.html')).href;await page.goto(url);
 assert.equal(await page.locator('[data-work-queue]').count(),3);
 await page.locator('[data-work-queue=pending]').click();assert.ok(await page.locator('[data-request]').count()>=2);
 await page.locator('nav [data-page=personnel]').click();await page.locator('[data-confirm-personnel]').click();
 await page.locator('[data-select-person="P-DEMO-1"]').check();await page.locator('#personnel-bulk-form [name=status]').selectOption('휴가');await page.locator('#personnel-bulk-form [name=end]').fill('2026-09-18');await page.locator('#personnel-bulk-form .primary').click();
 assert.equal(await page.locator('[data-confirm-personnel]').isEnabled(),true);await page.locator('[data-undo-personnel]').click();assert.equal(await page.locator('[data-confirm-personnel]').isDisabled(),true);
 await page.locator('[data-select-person="P-DEMO-1"]').check();await page.locator('#personnel-bulk-form [name=status]').selectOption('휴가');await page.locator('#personnel-bulk-form [name=end]').fill('2026-09-18');await page.locator('#personnel-bulk-form .primary').click();
 await page.locator('#staffing-date').fill('2026-09-19');assert.match(await page.locator('[data-person-id="P-DEMO-1"]').textContent(),/주간/);
 await page.reload();await page.locator('nav [data-page=personnel]').click();assert.match(await page.locator('[data-person-id="P-DEMO-1"]').textContent(),/휴가/);
 await page.locator('[data-edit-person="P-DEMO-2"]').click();await page.locator('#personnel-form [name=name]').fill('취소할 이름');await page.locator('[data-cancel-staffing]').click();assert.match(await page.locator('[data-person-id="P-DEMO-2"]').textContent(),/가상 나래/);
 await page.locator('[data-edit-person="P-DEMO-2"]').click();await page.locator('#personnel-form [name=name]').fill('가상 나래 수정');await page.locator('#personnel-form .primary').click();assert.match(await page.locator('[data-person-id="P-DEMO-2"]').textContent(),/가상 나래 수정/);
 await page.locator('[data-confirm-personnel]').click();await page.screenshot({path:'tmp/test-results/operations-preview-personnel.png',fullPage:true,style:'#feedback{visibility:hidden}'});
 await page.locator('nav [data-page=duty]').click();await page.locator('[data-edit-duty]').click();assert.equal(await page.locator('[data-copy-duty]').isDisabled(),true);
 await page.evaluate(()=>{const roster=structuredClone(M.dutyOn(state,M.today));M.saveDutyOn(state,'2026-09-15',{...roster,start:'2026-09-15T18:00',end:'2026-09-16T09:00'});openDuty();});await page.locator('[data-copy-duty]').click();
 await page.locator('[data-roster-search="D-DEMO-1"]').fill('가온');await page.locator('[data-roster-select="D-DEMO-1"]').selectOption('P-DEMO-1');
 assert.equal(await page.locator('#duty-form [name="name-D-DEMO-1"]').inputValue(),'가상 가온');assert.equal(await page.locator('#duty-form [name="rank-D-DEMO-1"]').isDisabled(),true);
 page.once('dialog',d=>d.dismiss());await page.locator('nav [data-page=dashboard]').click();assert.equal(await page.locator('#duty-form').count(),1);
 page.once('dialog',d=>d.dismiss());await page.locator('#demo-role').selectOption('user');assert.equal(await page.locator('#demo-role').inputValue(),'bnoc');
 await page.screenshot({path:'tmp/test-results/operations-preview-duty-edit.png',fullPage:true,style:'#feedback{visibility:hidden}'});await page.locator('#duty-form .primary').click();await page.screenshot({path:'tmp/test-results/operations-preview-duty.png',fullPage:true,style:'#feedback{visibility:hidden}'});
 await page.locator('nav [data-page=dashboard]').click();assert.match(await page.locator('.duty-table').textContent(),/가상 가온/);await page.screenshot({path:'tmp/test-results/operations-preview-integrated.png',fullPage:true,style:'#feedback{visibility:hidden}'});
 await page.reload();assert.match(await page.locator('.duty-table').textContent(),/가상 가온/);
 await page.locator('nav [data-page=equipment]').click();await page.locator('#equipment-add').click();await page.locator('#equipment-batch-form [name=name]').fill('저장 확인 장비');await page.locator('#equipment-batch-form [name=project]').fill('테스트 사업');await page.locator('#equipment-batch-form [name=year]').fill('2026');await page.locator('#equipment-batch-form .primary').click();await page.waitForFunction(()=>!document.querySelector('#dialog').open);
 await page.reload();await page.locator('nav [data-page=equipment]').click();await page.locator('#equipment-rows').filter({hasText:'저장 확인 장비'}).waitFor();
 await page.locator('[data-equipment-tab=security]').click();await page.locator('[data-equipment-edit="1"]').click();await page.locator('#equipment-form [name=file]').setInputFiles({name:'demo.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 demo')});await page.locator('#equipment-form .primary').click();await page.locator('#feedback').filter({hasText:'첨부파일을 이 브라우저에 저장'}).waitFor();
 await page.reload();await page.locator('nav [data-page=equipment]').click();await page.locator('[data-equipment-tab=security]').click();await page.locator('[data-equipment-document]').filter({hasText:'demo.pdf'}).waitFor();
 const download=page.waitForEvent('download');await page.locator('[data-equipment-document]').filter({hasText:'demo.pdf'}).click();assert.equal((await download).suggestedFilename(),'demo.pdf');
 await page.screenshot({path:'tmp/test-results/operations-preview-equipment.png',fullPage:true});
 await page.goto(pathToFileURL(path.resolve('docs/design/mockup/index.html')).href+'#equipment');await page.waitForURL('**/mockup.html?page=equipment');await page.locator('#equipment-rows').filter({hasText:'저장 확인 장비'}).waitFor();
 await page.locator('#demo-role').selectOption('user');assert.equal(await page.locator('nav [data-page=equipment]').isVisible(),false);assert.equal(await page.locator('nav [data-page=personnel]').isVisible(),false);assert.equal(await page.locator('[data-confirm-personnel]').count(),0);
 await page.locator('#demo-role').selectOption('bnoc');await page.locator('[data-account-open]').click();await page.locator('.account-demo-tools summary').click();page.once('dialog',d=>d.accept());const reload=page.waitForEvent('load');await page.locator('[data-reset-demo]').click();await reload;await page.locator('nav [data-page=personnel]').click();assert.match(await page.locator('[data-person-id="P-DEMO-1"]').textContent(),/주간/);
 await page.evaluate(()=>{Storage.prototype.setItem=function(){throw new DOMException('quota','QuotaExceededError');};});await page.locator('[data-confirm-personnel]').click();assert.match(await page.locator('#demo-storage-status').textContent(),/저장에 실패/);
 assert.deepEqual(errors,[]);console.log('PASS operations: periods/checks/undo, roster, dirty guard, storage/failure, equipment attachments, redirect, reset');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
