const {launchBrowser}=require('./browser.cjs'),assert=require('node:assert/strict'),path=require('node:path'),{pathToFileURL}=require('node:url');
(async()=>{const browser=await launchBrowser();try{
const p=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://api.open-meteo.com/**',r=>r.abort());await p.goto(pathToFileURL(path.resolve('docs/design/mockup.html')).href);await p.evaluate(()=>equipmentReady);
assert.equal(await p.locator('.workspace #current-account').count(),0);assert.equal(await p.locator('.topbar #current-account').count(),1);await p.locator('[data-account-open]').click();assert.match(await p.locator('.account-facts').first().textContent(),/第|제17/);await p.locator('#close').click();
await p.evaluate(()=>{document.documentElement.dataset.theme='dark';page='statistics';render();});
for(const [cls,color] of [['added','rgb(82, 211, 180)'],['completed','rgb(121, 183, 255)']]){const b=p.locator('.trend-column.'+cls+'-fill').first();assert.equal(await b.evaluate(e=>getComputedStyle(e).backgroundColor),color);await b.hover();assert.equal(await b.evaluate(e=>getComputedStyle(e).backgroundColor),color);}
await p.screenshot({path:'tmp/test-results/review-dark-statistics.png',fullPage:true});
const plan=await p.evaluate(()=>{const plan=SO.savePlan(state,{target:'switch',title:'화면 검증 계획정비',start:M.today+'T20:00',end:M.today+'T21:00',impact:'일부 제한',scope:'검증 범위',status:'예정',department:'network'});page='progress';render();return plan;});
assert.ok(plan.taskId.startsWith('W-PLAN-'));assert.doesNotMatch(await p.locator('#content').innerText(),/W-PLAN-|R-PLAN-/);await p.locator('[data-task="'+plan.taskId+'"]').first().click();assert.doesNotMatch(await p.locator('#dialog-body').innerText(),/W-PLAN-|R-PLAN-/);await p.locator('#close').click();
await p.locator('nav [data-page=equipment]').click();await p.locator('#equipment-add').click();await p.locator('#equipment-batch-form [name=project]').fill('행 추가 검증 사업');await p.locator('#equipment-batch-form [name=year]').fill('2026');await p.locator('#equipment-batch-rows [name=name]').fill('검증 장비 A');await p.locator('#equipment-row-add').click();await p.locator('#equipment-batch-rows [name=name]').nth(1).fill('검증 장비 B');await p.locator('#equipment-row-add').click();await p.locator('[data-remove-row]').last().click();assert.equal(await p.locator('#equipment-batch-rows tr').count(),2);await p.screenshot({path:'tmp/test-results/review-equipment-batch.png'});await p.locator('#equipment-batch-form .primary').click();await p.waitForFunction(()=>!document.querySelector('#dialog').open);assert.equal(await p.locator('#equipment-rows tr').count(),2);
await p.reload();await p.evaluate(()=>equipmentReady);await p.locator('nav [data-page=equipment]').click();await p.locator('#equipment-search').fill('행 추가 검증 사업');assert.equal(await p.locator('#equipment-rows tr').count(),2);await p.locator('[data-equipment-delete]').first().click();await p.locator('[name=confirmName]').fill('틀린 이름');await p.locator('#equipment-delete-form .primary').click();assert.match(await p.locator('#equipment-delete-form .error').textContent(),/일치/);await p.locator('[name=confirmName]').fill('검증 장비 A');await p.locator('#equipment-delete-form .primary').click();await p.waitForFunction(()=>!document.querySelector('#dialog').open);assert.equal(await p.locator('#equipment-rows tr').count(),1);
await p.evaluate(()=>{const linked=operationNodes().find(n=>n.equipmentId);deleteEquipment(linked.equipmentId);});assert.equal(await p.locator('#dialog-title').textContent(),'장비 삭제 불가');await p.locator('#close').click();
await p.reload();await p.evaluate(()=>equipmentReady);assert.equal(await p.evaluate(()=>equipment.filter(e=>e.project==='행 추가 검증 사업').length),1);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));assert.deepEqual(errors,[]);console.log('PASS: sidebar identity, dark charts/hover, plan labels, batch add/remove/save/reload, guarded deletion');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
