const {launchBrowser}=require('./browser.cjs'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path');
(async()=>{const browser=await launchBrowser();try{
const p=await browser.newPage({viewport:{width:1366,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://api.open-meteo.com/**',r=>r.abort());await p.goto(pathToFileURL(path.resolve('docs/design/mockup.html')).href);await p.evaluate(()=>equipmentReady);
await p.locator('#demo-role').selectOption('user');assert.equal(await p.locator('nav [data-page=personnel]:visible').count(),0);await p.locator('nav [data-page=duty]').click();assert.equal(await p.evaluate(()=>canVisit('personnel')),false);assert.equal(await p.evaluate(()=>dailyReport(M.today).length),3);
await p.locator('#demo-role').selectOption('network');assert.equal(await p.evaluate(()=>canVisit('personnel')),true);
await p.locator('#demo-role').selectOption('bnoc');await p.locator('nav [data-page=requests]').click();assert.equal(await p.locator('#request-form [name=requester]').isEditable(),true);
const result=await p.evaluate(()=>{const req=M.createRequest(state,{requester:'전화 요청 부서',target:'검증 장비',type:'점검',description:'대리 접수 검증',wish:'network',tag:'PC'});M.assign(state,req.id,'network','PC');const task=state.tasks.find(t=>t.requestId===req.id),before=state.tasks.length;const plan=SO.savePlan(state,{target:'switch',title:'연결 검증',start:M.today+'T19:00',end:M.today+'T20:00',impact:'일부 제한',scope:'검증 구역',status:'예정',taskId:task.id});const linked=state.tasks.length===before;SO.savePlan(state,{...plan,status:'취소'},plan.id);const intact=!task.cancelled&&!req.cancelled;state.role='network';M.updateTask(state,task.id,{tag:'PC',status:'조치 완료',note:'검증 완료'});const cancelled=operationPlans().find(p=>p.id===plan.id).status==='취소';state.role='bnoc';const fresh=SO.savePlan(state,{target:'switch',title:'새 계획정비',start:M.today+'T20:00',end:M.today+'T21:00',impact:'일부 제한',scope:'검증 구역',status:'예정',department:'network'});state.role='network';M.updateTask(state,fresh.taskId,{tag:'PC',status:'조치 완료',note:'새 계획 완료'});state.role='viewer';refreshSharedWing();const shared=V.wings.find(w=>w.id==='17').records.find(t=>t.id===fresh.taskId);state.role='bnoc';const n=operationNodes().find(n=>n.kind==='장비'),a=equipment.find(a=>a.id===n.equipmentId);a.name='공통 장비명 검증';render();return {owner:req.owner,linked,intact,cancelled,completed:fresh.status,shared:shared.completed,name:n.name,notice:state.notifications.filter(n=>n.requestId===req.id&&n.kind==='새 정비 요청').length};});
assert.equal(result.owner,'proxy');for(const key of ['linked','intact','cancelled'])assert.equal(result[key],true,key);assert.equal(result.completed,'완료');assert.ok(result.shared);assert.equal(result.name,'공통 장비명 검증');assert.equal(result.notice,1);assert.equal(await p.locator('[data-report]').count(),0);await p.evaluate(()=>{equipmentTab='security';page='operations';operationTab='structure';operationSelected='switch';render();});await p.locator('[data-linked-asset]').click();assert.equal(await p.locator('[data-equipment-tab=inventory]').getAttribute('aria-selected'),'true');assert.match(await p.locator('#equipment-rows').textContent(),/공통 장비명 검증/);await p.locator('nav [data-page=instructions]').click();await p.locator('[data-add-instruction]').click();await p.locator('#instruction-input [name=title]').fill('직접 게시 검증');await p.locator('#instruction-input [name=source]').fill('입력 내용 그대로 게시');await p.locator('#instruction-input .primary').click();assert.equal(await p.locator('#instruction-review [name=itemBody0]').inputValue(),'입력 내용 그대로 게시');await p.locator('#instruction-review input[type=checkbox]').check();await p.locator('#instruction-review .primary').click();assert.match(await p.locator('#instruction-panel').textContent(),/직접 게시 검증/);assert.deepEqual(errors,[]);console.log('PASS workflow: role permissions, proxy intake, single notifications, existing/new plan links, cancellation isolation, completion/viewer sync, shared equipment');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
